accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    
]

projectWebsite/urls.py
from django.contrib import admin
from django.urls import path, include # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # new
]

accounts/models.py
from django.db import models
# # Create your models here.

# class Register(models.Model):
#     nama = models.CharField(max_length=40)
#     password = models.CharField(max_length=20)
#     reenterpsw = models.CharField(max_length=20)

# class Login (models.Model):
#     nama = models.CharField(max_length=40)
#     password = models.CharField(max_length=20)

accounts/forms.py
from django import forms
# from . import models

# class RegisterTutee(forms.ModelForm):
#     class Meta:
#         model = models.Register
#         fields = ['nama', 'password', 'reenterpsw']
# class LoginTutee(forms.ModelForm):
#     class Meta:
#         model = models.Login
#         fields = ['nama','password']       

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.
def signup_view (request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            #log the user in
            return redirect(signup)#belom fix, nanti return ke home 
    else:
        form = UserCreationForm()
    return render (request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log the user in
            user=form.get_user()
            login(request,user)
            return redirect(signup)#belom fix, harusnya nanti di return ke home
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form':form})        

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect(signup) #belom fix juga

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>LOGIN</h1>
    <form   class='site-form' action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Login">
        </input>

    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>SIGNUP</h1>
    <form   class='site-form' action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
        </input>

    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}A{% endblock %}</title>
  <nav>
    <ul>
      <li>
        <form class = "logout-link" action = "{% url 'accounts:logout' %}" method="post">
          {%csrf_token%}
          <button type="submit">Logout</button>
        </form>
      </li>
    </ul>
  </nav>
</head>
<body bgcolor="#ECFCFF">
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}